#-------------------------------------------------------------------------------
# Setup
#-------------------------------------------------------------------------------
# Reference article (last referenced 10/7/19):
# https://lorisleiva.com/laravel-deployment-using-gitlab-pipelines/

image: lorisleiva/laravel-docker:latest

stages:
  - build
  - test
  - deploy

variables:
  VAPOR_API_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYmZkM2E3NzA4M2RmMDQxMzhhMjk3YTEyYmQ1NTRiZThmZDA1YjIzNTQxMzg0MzMzM2U1NmQ3YTUyYzNiMmFjZjE0ZTI1NWNlNjAwYzU5ZTgiLCJpYXQiOjE1OTcwMDcxMzIsIm5iZiI6MTU5NzAwNzEzMiwiZXhwIjoxNjI4NTQzMTMyLCJzdWIiOiIyNTI4Iiwic2NvcGVzIjpbIioiXX0.aS-5YkgLxKrIJ2bZCO0n-CNd9f-Kcumw3dsIajimoDHRLNZkbon_uGVrH9AS03J6kaW4i5u58CAbHZcvC51LspV2j2yqhyAsrO0c_Ybe_AH8twyhxlo6IGvBGCmXhx0yy0eqf9DAR8q108cW2XWo26t3PkuuX4KLYMqwauEHx3wFtHnXCEuDalImrSu6W8T0WzmRw06PpmmCbLac-4ZqEjFrYYOfiSiKlBUzXdqf2V0wgLTxt1KF-qXbCe6NQjZUZrlxTV6YZG3HLemvkFC3n5GIjDVCfQGnTY5RELPWZVgeLZLulSiThg5DuyT01MYevtTk9jvdlliyvC7dxVBEryna_ceIo0Z2jgzbhKQVTLeatcPyYOgHHtpIgl8jqq7_0fJgSWAgB6cAjDAun4JDLkSjQzrAGwEoT0oQEDlcdg35yzo6LZtvkjkXJ1CLG8vuEsgvo3hUhmW3KxlZ9W8A6qI5nKTh8D72p52R33JisaU5BMsoIkE1vpbO47TfeZSPrLgXK8u5n0uR1SZFFpfw_bZA_z5ov-rnqzBQ_OA_24ZzFjtmlMApDVWwowMJ_GMGpiqv9U4XZMsacAYzyeDSyhj9nHFc5W9A4xv3Ff2IiMFOsopIfmr6vdD6-jHAxjGkFCo4y9mxvL9qSKJoKkU3U6HRzK4W4fDuNVplDsZb6tw"
#-------------------------------------------------------------------------------
# Build
#-------------------------------------------------------------------------------
composer:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.testing .env
    - php artisan key:generate
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env

npm:
  stage: build
  script:
    - npm install
    - npm run production
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/css/
      - public/js/

#-------------------------------------------------------------------------------
# Test
#-------------------------------------------------------------------------------
jest: 
  stage: test
  script:
    - npm test
    
phpunit: 
  stage: test
  script:
    - phpunit

#-------------------------------------------------------------------------------
# Deploy
#-------------------------------------------------------------------------------
vapor:
  stage: deploy
  script:
    - vapor deploy production
